# =============================================================================
# config.nu — main Nushell config. Loaded AFTER env.nu.
#
# This file holds only CORE settings + keybindings, then sources the topical
# files below (mirrors your zsh/.zsh/*.zsh split so you can review each piece):
#   git.nu        OMZ git plugin aliases
#   arch.nu       pacman/paru + system aliases
#   aliases.nu    general aliases (eza, grep, rsync, pip, edit-config)
#   functions.nu  ex, clang-format-all, psgrep, e
#   fzf.nu        forgit `gd`, `fed`, `fim`
# Prompt + zoxide init are sourced last (generated by env.nu).
# =============================================================================

# --- Core behaviour (zsh options.zsh / history.zsh / history-search.zsh) ---
$env.config.edit_mode = "vi"            # bindkey -v
$env.config.show_banner = false
$env.config.buffer_editor = $env.EDITOR # Ctrl-o edits the line in nvim (vim fallback)

$env.config.history = {
  max_size: 500_000                     # SAVEHIST
  sync_on_enter: true                   # inc_append_history
  file_format: "sqlite"                 # better dedup than the plain text file
  isolation: false                      # false = shared history (share_history)
}

$env.config.completions = {
  case_sensitive: false
  quick: true                           # auto-complete on unique match
  partial: true
  algorithm: "fuzzy"                    # fuzzy matching
}

$env.config.cursor_shape = {
  vi_insert: line
  vi_normal: block
  emacs: line
}

$env.config.rm.always_trash = false

# -----------------------------------------------------------------------------
# Keybindings (zsh history-search.zsh + fzf.zsh)
# Native Ctrl-r fuzzy history menu is kept. Added: Ctrl-t fzf file picker,
# Ctrl-o edit-line-in-$EDITOR. (Helpers gd/fed/fim live in fzf.nu.)
# -----------------------------------------------------------------------------
$env.config.keybindings = [
  {
    name: fzf_files
    modifier: control
    keycode: char_t
    mode: [vi_normal vi_insert emacs]
    event: {
      send: executehostcommand
      cmd: "commandline edit --insert (fd --type f --follow --exclude .git | fzf --preview 'bat --color=always {} 2> /dev/null | head -200' | str trim)"
    }
  }
  {
    name: edit_in_editor
    modifier: control
    keycode: char_o
    mode: [vi_normal vi_insert emacs]
    event: { send: openeditor }
  }
]

# -----------------------------------------------------------------------------
# Source the topical files. `source` needs a parse-time const path; using
# $nu.default-config-dir keeps it correct through the stow symlink.
# -----------------------------------------------------------------------------
const fns_nu     = ($nu.default-config-dir | path join functions.nu)
source $fns_nu
const git_nu     = ($nu.default-config-dir | path join git.nu)
source $git_nu
const arch_nu    = ($nu.default-config-dir | path join arch.nu)
source $arch_nu
const aliases_nu = ($nu.default-config-dir | path join aliases.nu)
source $aliases_nu
const fzf_nu     = ($nu.default-config-dir | path join fzf.nu)
source $fzf_nu

# -----------------------------------------------------------------------------
# starship prompt + zoxide (`z`). Generated by env.nu into <data-dir>/init/.
# -----------------------------------------------------------------------------
const starship_init = ($nu.data-dir | path join init starship.nu)
source $starship_init
const zoxide_init = ($nu.data-dir | path join init zoxide.nu)
source $zoxide_init
