-- Tabularize
vim.keymap.set({ "n", "v" }, "<Leader>a&", ":Tabularize /&<CR>", { desc = "Align: by &" })
vim.keymap.set({ "n", "v" }, "<Leader>a=", ":Tabularize /^[^=]*\zs=<CR>", { desc = "Align: by =" })
vim.keymap.set({ "n", "v" }, "<Leader>a=>", ":Tabularize /=><CR>", { desc = "Align: by =>" })
vim.keymap.set({ "n", "v" }, "<Leader>a:", ":Tabularize /: <CR>", { desc = "Align: by :" })
vim.keymap.set({ "n", "v" }, "<Leader>a::", ":Tabularize /: \zs<CR>", { desc = "Align: by ::" })
vim.keymap.set({ "n", "v" }, "<Leader>a,", ":Tabularize /,<CR>", { desc = "Align: by ," })
vim.keymap.set({ "n", "v" }, "<Leader>a,,", ":Tabularize /,\zs<CR>", { desc = "Align: by ,," })
vim.keymap.set({ "n", "v" }, "<Leader>a<Bar>", ":Tabularize /<Bar><CR>", { desc = "Align: by |" })
vim.keymap.set({ "n", "v" }, "<Leader>a\\", ":Tabularize /\\<CR>", { desc = "Align: by \\" })
