# ansible/inventory.ini
[work]
dev-machine.local ansible_connection=local
mac-studio.local ansible_connection=local
win-dev.local ansible_connection=local
macbook-pro.local ansible_connection=local

[personal]
personal-desktop-arch.local ansible_connection=local
personal-desktop-win.local ansible_connection=local

[work:children]
work_linux
work_macos
work_windows

[personal:children]
personal_linux
personal_windows

[linux:children]
work_linux
personal_linux

[macos:children]
work_macos

[windows:children]
work_windows

[work_linux]
dev-machine.local

[work_macos]
mac-studio.local
macbook-pro.local

[work_windows]
win-dev.local

[personal_linux]
personal-desktop-arch.local

[personal_windows]
personal-desktop-win.local
